import imgOne from '../src/images/P-13-3.jpg';
import imgTwo from '../src/images/P-19-1.jpg';
import imgThree from '../src/images/P-26.jpg';
import imgFour from '../src/images/P-35-3.jpg';
import imgFive from '../src/images/P-56-1.jpg';

const details = [
	{
		painter: "Acheloos Painter",
		img: imgOne,
		shape: "Alabastron",
		location: "Turkey, Asia Minor",
		citationNumber: 1,
		vaseNumber: 4703,
		description: "amazon, with pick and pelta with apron, altar, palm tree, device, eye",
		reference: "corpus vasorum antiquorum: karlsruhe, badisches landesmuseum 3, 55-56, beilage 1.1, 1.2, pl.(2970)",
		subject: "AGAMEMNON",
		technique: "Added color",
		subTechnique: "Added color",
		collection: "Bologna, Museo Civico Archeologico",
		date: "200-100",
		incription: "Kalos"
	},
	{
		painter: "Achilles Painter",
		img: imgTwo,
		shape: "Amphora",
		location: "Turkey, Asia Minor",
		citationNumber: 2,
		vaseNumber: 4703,
		description: "amazon, with pick and pelta with apron, altar, palm tree, device, eye",
		reference: "corpus vasorum antiquorum: karlsruhe, badisches landesmuseum 3, 55-56, beilage 1.1, 1.2, pl.(2970)",
		subject: "AIGINA",
		technique: "Added red",
		subTechnique: "Added color",
		collection: "Bologna, Museo Civico Archeologico",
		date: "300-200",
		incription: "Kale"
	},
	{
		painter: "Acropolis 606, P of",
		img: imgThree,
		shape: "ALTAR",
		location: "London, British museum",
		citationNumber: 3,
		vaseNumber: 4831,
		description: "maenads wearing leopard skins, with branches",
		reference: " algrain, i., l alabastre attique. origine, forme et usages (brussels, 2014): 47, fig.8 (part of bd)",
		subject: "ALTAR",
		technique: "Aquarell",
		subTechnique: "Added white",
		collection: "Bologna, Museo Civico Archeologico",
		date: "400-300",
		incription: "Egraphsen"
	},
	{
		painter: "Aegisthus Painter",
		img: imgFour,
		shape: "Aryballos",
		location: "Italy, spina",
		citationNumber: 4,
		vaseNumber: 4974,
		description: "youth with staff, man with phiale, both draped, kalathos on ground",
		reference: "corpus vasorum antiquorum: bochum, kunstsammlungen der ruhr-universitat 2, 65, pl.(4220) 68.1-4",
		subject: "AMAZONOMACHY",
		technique: "BASE-RING WARE",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "300-200",
		incription: "425-375"
	},
	{
		painter: "Affecter",
		img: imgFive,
		shape: "Askos",
		location: "Geneva, Musée d'Art et d'Histoire",
		citationNumber: 5,
		vaseNumber: 4974,
		Description: "eros, flying over altar with wreath, youth, stool",
		reference: " corpus vasorum antiquorum: geneva, musee d'art et d'histoire 2, 56-57, pl.(135) 79.5-8",
		subject: "AMAZONS",
		technique: "BICHROME",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "450-400",
		incription: "Graffito"
	},
	{
		painter: "Aison",
		img: imgOne,
		shape: "Astragalos",
		location: "Geneva, London, market, Sotheby’s",
		citationNumber: 6,
		vaseNumber: 5743,
		description: "athletes, acontist, diskobolos, and with halteres, youth in chiton playing pipes",
		reference: "Sotheby, sale catalogue: 8.12.1980, NO.254",
		subject: "AMPHORA",
		technique: "BLACK BODIED",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "475-425",
		incription: "Patronymic"
	},
	{
		painter: "Amasis",
		img: imgTwo,
		shape: "Bail Vase",
		location: "London, market, Ede",
		citationNumber: 7,
		vaseNumber: 5803,
		description: "pattern, net, meander and tongues",
		reference: "charles ede, sale catalogue: pottery from athens, iii(1976), no.1",
		subject: "ANIMAL",
		technique: "BLACK GLAZE",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "500-450",
		incription: "Signature"

	},
	{
		painter: "Amasis Painter",
		img: imgThree,
		shape: "Ball",
		location: "london, market, sotheby's",
		citationNumber: 8,
		vaseNumber: 7084,
		description: "naked woman washing at laver",
		reference: "PHOTOGRAPH(S) IN THE BEAZLEY ARCHIVE: 7 Sotheby, sale catalogue: 11 - 12.7.1983, 97, NO.314(COLOUR)Sotheby, sale catalogue: 14 - 15.12.1981, 133, NO.347(COLOUR)",
		subject: "APHLASTA",
		technique: "BLACK PATTERN",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "525-475",
		incription: "All"
	},
	{
		painter: "Amazon Painter",
		img: imgFour,
		shape: "Balsamarion",
		location: "Berlin, Schloss Charlottenburg",
		citationNumber: 9,
		vaseNumber: 7758,
		description: "draped youth seated with staff receiving phiale from woman holding oinochoe, cat, basket suspended",
		reference: " Corpus Vasorum Antiquorum: BERLIN, ANTIKENSAMMLUNG 16, 37, 38, 39, FIG.6, BEILAGE 2.2, PLS.(4913, 4914) 10.1-7, 11.1-2",
		subject: "ARMING",
		technique: "BLACK POLISHED WARE",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "550-500" ,
		incription: ""
	},
	{
		painter: "Amykos Painter",
		img: imgFive,
		shape: "Basin",
		location: "Italy, Sicily, selinus",
		citationNumber: 10,
		vaseNumber: 7810,
		description: "woman at laver",
		reference: "Odeon ed altri monumenti archeologici(Palermo, 1971): PL.61C",
		subject: "ATHLETES",
		technique: "BLACK POLYCHROME",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "575-525" ,
		incription: ""
	},
	 {
		painter: "Analatos P (Protoattic)",
		img: imgOne,
		shape: "Basket",
		location: "Paris, Musée du Louvre",
		citationNumber: 11,
		vaseNumber: 7838,
		description: "apollo with kithara, dionysos, hermes, deer, panther, goat, artemis",
		reference: "Algrain, I., L'alabastre attique. Origine, forme et usages (Brussels, 2014): 104, FIG.49 (PART OF BD). Haspels, C., Attic Black-figured Lekythoi (Paris, 1936): 237.109, PL.37.4A-D. Lexicon Iconographicum Mythologiae Classicae: II, PL.253, APOLLON 781D",
		subject: "ATTACKING",
		technique: "BLACK SLIP WARE",
		subTechnique: "BLACK-FIGURE",
		collection: "Bologna, Museo Civico Archeologico",
		date: "600-550" ,
		incription: ""
	}
];

export default details;